name: CI

on:
  workflow_dispatch:
jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write .npmrc
        run: echo '//verdaccio.urip13.duckdns.org/:_authToken="${{ secrets.NPM_TOKEN }}"' >> ~/.npmrc
      - name: print
        run: echo ~/.npmrc
